[tox]
envlist = py311,py312
isolated_build = True
skip_missing_interpreters = True

[testenv]
deps =
    requests
    pydantic
commands =
    python tests/test_import.py

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12